remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: GiftCardMall MyGift Balance: Easy Checking Guide
description: Navigating the world of gift cards is easy with giftcardmall mygift balance feature in place. Users can now stay on top of their gift card balances with ease.
